In [1]:
pip install tensorflow


In [3]:
import tensorflow as tf
import numpy as np
print("tensor version: ", tf.__version__)

tensor version:  2.19.0


In [5]:
scalar=tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [6]:
vector=tf.constant([1,2,3])
print(vector)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [7]:
matrix=tf.constant([[1,2,3],[4,5,6]])

In [8]:
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [9]:
a=tf.constant([20,30,40])
b=tf.constant([1,2,3])
print(a+b)

tf.Tensor([21 32 43], shape=(3,), dtype=int32)


In [10]:
a=tf.constant([20,30,40])
b=tf.constant([1,2,3])
print(a*b)

tf.Tensor([ 20  60 120], shape=(3,), dtype=int32)


In [12]:
a=tf.constant([20,30,40])
b=tf.constant([3,2,6])
print(a/b)


tf.Tensor([ 6.66666667 15.          6.66666667], shape=(3,), dtype=float64)


In [13]:
a=tf.constant([20,30,40])
b=tf.constant([1,2,3])
print(a-b)

tf.Tensor([19 28 37], shape=(3,), dtype=int32)


In [16]:
a=tf.constant([20,30,40])
print(a.dtype, a.shape, tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


In [17]:
a=tf.constant([[20,30,40],[2,4,6]])
print(a.dtype, a.shape, tf.rank(a))

<dtype: 'int32'> (2, 3) tf.Tensor(2, shape=(), dtype=int32)


In [22]:
#converting numpy to tensor
np_arr=np.array([[1,2,3],[2,3,4]])
tensor=tf.convert_to_tensor(np_arr)

print(np_arr)
print("************************")
print(tensor)

[[1 2 3]
 [2 3 4]]
************************
tf.Tensor(
[[1 2 3]
 [2 3 4]], shape=(2, 3), dtype=int64)
