In [4]:
# Import libraries
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Step 1: Corpus (dataset)
corpus = [
    "deep learning is powerful",
    "deep learning is fun",
    "machine learning is interesting",
    "artificial intelligence is the future",
    "i love machine learning",
    "lstm is used for sequence prediction",
    "neural networks learn patterns",
    "data science is exciting",
    "python is easy to learn",
    "models improve with more data",

    "ai is transforming the world",
    "big data drives decision making",
    "deep learning uses neural networks",
    "supervised learning requires labeled data",
    "unsupervised learning finds hidden patterns",
    "reinforcement learning learns by rewards",
    "python is widely used in data science",
    "tensorflow and pytorch are popular frameworks",
    "data preprocessing is important in machine learning",
    "feature engineering improves model performance",
    "overfitting reduces model generalization",
    "cross validation helps evaluate models",
    "natural language processing deals with text data",
    "computer vision works with images",
    "models need training and testing data",
    "gradient descent optimizes the loss function",
    "activation functions introduce non linearity",
    "backpropagation updates model weights",
    "large datasets improve accuracy",
    "cloud computing supports scalable ai systems"
]

print("Total sentences:", len(corpus))

# Step 2: Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)

total_words = len(tokenizer.word_index) + 1
print("Total unique words:", total_words)

# Step 3: Create input sequences
input_sequences = []

for line in corpus:
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences.append(n_gram_seq)

# Step 4: Padding
max_sequence_len = max([len(x) for x in input_sequences])

input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre')
print(input_sequences[:10])

# Step 5: Split data into X and y
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

# Convert y into one-hot encoding
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=total_words)

# Step 6: Build LSTM Model
model = Sequential()
model.add(Embedding(total_words, 64, input_length=max_sequence_len-1))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))

# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Model summary
model.summary()

# Step 7: Train model
model.fit(X, y, epochs=200, verbose=1)

# Step 8: Text Prediction Function
def predict_next_word(seed_text, next_words=3):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

        predicted = np.argmax(model.predict(token_list, verbose=0), axis=-1)

        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted:
                output_word = word
                break

        seed_text += " " + output_word

    return seed_text

# Step 9: Test Prediction
print("\nPrediction:")
print(predict_next_word("deep learning", 3))
print(predict_next_word("unsupervised learning", 3))

Total sentences: 30
Total unique words: 106
[[ 0  0  0  0  0  4  2]
 [ 0  0  0  0  4  2  1]
 [ 0  0  0  4  2  1 21]
 [ 0  0  0  0  0  4  2]
 [ 0  0  0  0  4  2  1]
 [ 0  0  0  4  2  1 22]
 [ 0  0  0  0  0  5  2]
 [ 0  0  0  0  5  2  1]
 [ 0  0  0  5  2  1 23]
 [ 0  0  0  0  0 24 25]]


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 0.0164 - loss: 4.6627  
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0902 - loss: 4.6480
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0820 - loss: 4.6322
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0820 - loss: 4.6057
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0738 - loss: 4.5518
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0738 - loss: 4.4649
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.0738 - loss: 4.3262
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0574 - loss: 4.3017
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0820 - loss: 4.2499
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.0820 - loss: 4.2211
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0902 - loss: 4.1989
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.0902 - 